### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by Tijo1011** [rmtuckerphx/skill-starter-basic#1]
Hey,  i managed to set up erverything quit well. The Backend in the Lambda work well. But when i try to use the Service Simulator from the developer.amazon Site, i got the Message from the Headline. 

when i copy the json from this request and put it in a Test of the Lambda Function, it goes through and give the correct response. 

What can cause this Problem?

**Comment by rmtuckerphx** [comment]
There is a bug in the Service Simulator. See https://forums.developer.amazon.com/questions/79090/bug-in-service-simulator.html
